# Introduction to Pytorch and Tensors

## What is PyTorch?

PyTorch is an open-source deep learning framework developed by Facebook's AI Research lab 

It is popular among researchers and developers because of its dynamic computational graph, ease of use, and strong community support.

Several large companies currently use PyTorch to develop and deploy models (Facebook, Tesla, to name a few)

In [36]:
# Importing PyTorch
import torch
torch.__version__

'2.3.0'

## So, what are tensors?

Tensors are a fundamental concept in both mathematics and machine learning, especially in frameworks like PyTorch and TensorFlow. In essence, tensors are multi-dimensional arrays, similar to matrices but generalized to more dimensions. They are used to represent data in various forms and are the basic data structures that machine learning models operate on!


### Creating our first tensors 

Creating tensors in PyTorch is straightforward and flexible. PyTorch provides multiple ways to create tensors, whether you're starting with raw data, generating them programmatically, or creating them with specific properties like all zeros or ones. Let's look at some of those ways:

In [9]:
# Here we create our first tensor
scalar = torch.tensor(8)
scalar

tensor(8)

In [10]:
# You will note that it has 0 dimensions, which makes it a scalar!
scalar.ndim

0

In [11]:
scalar.dtype

torch.int64

In [13]:
# Vector
vector = torch.tensor([1, 2])
vector

tensor([1, 2])

In [14]:
# Our Vector has 1 dimension
vector.ndim

1

In [7]:
# Checking the shape of our vector
vector.shape

torch.Size([2])

In [15]:
# Matrix
matrix = torch.tensor([[7, 8], 
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
# Check number of dimensions
matrix.ndim

2

In [17]:
matrix.shape

torch.Size([2, 2])

In [18]:
# Creating a tensor
tensor1 = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
tensor1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
# Check number of dimensions for TENSOR
tensor1.ndim

3

In [13]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

### General Interpretation of a 3D Tensor

A 3D tensor has three dimensions, which are often interpreted as follows:

#### First Dimension (Depth, Batch, or Number of Samples):
- This dimension usually represents the number of distinct elements or samples in the tensor.
- For example, in a batch of images, this dimension might represent the batch size (number of images in the batch). If the tensor represents sequences (like in NLP tasks), this might represent the number of sequences.
- **Example:** If the shape is `(10, 3, 224)`, the first dimension (`10`) might represent 10 samples, such as 10 images or 10 sequences.

#### Second Dimension (Height, Channel, or Features):
- This dimension often represents a secondary characteristic of each sample, such as the number of channels in an image (e.g., RGB channels), the height of an image, or the number of features in a dataset.
- For instance, in an image, this could be the number of channels (such as 3 for RGB images). In sequence data, it could be the number of features at each time step.
- **Example:** If the shape is `(10, 3, 224)`, the second dimension (`3`) might represent 3 color channels (Red, Green, Blue) in an image.

#### Third Dimension (Width, Sequence Length, or Time Steps):
- The third dimension often represents the size along another axis, such as the width of an image, the length of a sequence, or the number of time steps in time-series data.
- **Example:** If the shape is `(10, 3, 224)`, the third dimension (`224`) might represent 224 pixels in the width of each image.


### After creating some tensors using lists, let's create a random one

In [20]:
# Create a random tensor of size (3, 3)
random_tensor = torch.rand(size=(3, 3))
random_tensor, random_tensor.dtype

(tensor([[0.4225, 0.0497, 0.9643],
         [0.9037, 0.2701, 0.6928],
         [0.1357, 0.4981, 0.9683]]),
 torch.float32)

In [15]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Using torch.zeros 

In [21]:
# Tensor filled with zeros
zeros = torch.zeros(size=(3, 3))
zeros, zeros.dtype

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 torch.float32)

We can do the same to create a tensor of all ones except using [`torch.ones()` ](https://pytorch.org/docs/stable/generated/torch.ones.html) instead.

In [23]:
# Tensor filled with ones
ones = torch.ones(size=(3, 3))
ones, ones.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

### Using torch.arange

In [24]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# We can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Basic Tensor operations

Here we will look at some basic tensor operations to become familiar with tensor manipulation, since
Neural Networks are all about that!

In [26]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [27]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [28]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [29]:
# Subtracting and assigning to a new variable
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [30]:
# Adding and reassigning to a new variable
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [28]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [29]:
# Original tensor is still unchanged 
tensor

tensor([1, 2, 3])

However, it's more common to use the operator symbols like `*` instead of `torch.mul()`

In [30]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


### Matrix Multiplication: A Brief Overview

Matrix multiplication involves multiplying two matrices to produce a third matrix. Given matrices $A$ (size $m \times n$) and $B$ (size $n \times p$), the resulting matrix $C = A \times B$ has dimensions $m \times p$. Each element $c_{ij}$ in $C$ is computed as:

$$
c_{ij} = \sum_{k=1}^{n} A_{ik} \times B_{kj}
$$

**Example:**

For matrices $A$ and $B$:

$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}, \quad B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}
$$

The product $C = A \times B$ is:

$$
C = \begin{bmatrix} 19 & 22 \\ 43 & 50 \end{bmatrix}
$$

**Key Points:**
- Matrix multiplication is not commutative: $A \times B \neq B \times A$.
- It is associative and distributive over addition.

In PyTorch, you can perform matrix multiplication with `torch.mm(A, B)` or the `@` operator.


In [31]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [32]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [33]:
# Matrix multiplication
torch.mm(tensor, tensor)

tensor(14)

In [34]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

We can make matrix multiplication work between `tensor_A` and `tensor_B` by making their inner dimensions match.

One of the ways to do this is with a **transpose** (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:
* `torch.transpose(input, dim0, dim1)` - where `input` is the desired tensor to transpose and `dim0` and `dim1` are the dimensions to be swapped.
* `tensor.T` - where `tensor` is the desired tensor to transpose.

Let's try the latter.

In [38]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [39]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


### Exploring our tensor





In [31]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [32]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [33]:
print(f"Index where max value occurs: {x.argmax()}")
print(f"Index where min value occurs: {x.argmin()}")

Index where max value occurs: 9
Index where min value occurs: 0


### Tensor Manipulation: Reshaping, Stacking, and Squeezing

#### Reshaping
- **Reshaping** is the process of changing the shape (dimensions) of a tensor without altering its data. This is useful when you need to adjust the structure of a tensor to fit into a model or a specific operation.
- You can reshape a tensor using `torch.reshape()` or `tensor.view()`.

In [ ]:
# Example
tensor = torch.arange(12)
reshaped_tensor = tensor.view(3, 4)  # Reshape to 3x4 matrix

### Stacking

- **Stacking** involves joining a sequence of tensors along a new dimension. This operation is useful when you want to combine multiple tensors into a single tensor while adding an extra dimension.
- You can stack tensors using `torch.stack()`.

In [50]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
stacked_tensor = torch.stack([tensor1, tensor2])  # Shape will be (2, 3)


(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

### Squeezing

- **Squeezing** removes dimensions of size 1 from a tensor, effectively reducing the dimensionality without altering the data. This is particularly useful for eliminating unnecessary dimensions that can result from certain operations.
- You can squeeze a tensor using `torch.squeeze()`.

In [34]:
tensor = torch.tensor([[[1], [2], [3]]])  # Shape is (1, 3, 1)
squeezed_tensor = tensor.squeeze()  # Shape will be (3,)
print(squeezed_tensor)

tensor([1, 2, 3])


## Indexing (selecting data from tensors)

Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).

To do so, you can use indexing.

If you've ever done indexing on Python lists or NumPy arrays, indexing in PyTorch with tensors is very similar.

In [58]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

Indexing values goes outer dimension -> inner dimension (check out the square brackets).

In [59]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


You can also use `:` to specify "all values in this dimension" and then use a comma (`,`) to add another dimension.

In [60]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [61]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [62]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [63]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

### Summary

Tensors are the core data structures in PyTorch, acting as multi-dimensional arrays that store data. They are crucial for performing efficient computations, particularly in deep learning. Key concepts and operations include:

- **Reshaping:** Adjusting the dimensions of a tensor to match model requirements using functions like `view()` or `reshape()`.

- **Stacking:** Combining multiple tensors along a new dimension, useful for creating batches or merging data, using `torch.stack()`.

- **Squeezing:** Removing unnecessary dimensions of size 1 to simplify the tensor's shape with `torch.squeeze()`.

- **Tensor Operations:** Performing mathematical and logical operations on tensors, such as element-wise operations, reductions, and broadcasting, which are fundamental for building and training neural networks.

- **Matrix Multiplication:** A vital operation in neural networks, where two matrices are multiplied to produce a third matrix. This is commonly used in layers like fully connected layers and is performed in PyTorch using `torch.mm()` or the `@` operator.

Understanding these concepts allows you to manipulate tensors effectively, enabling the construction and optimization of deep learning models in PyTorch.
