In [5]:
#### 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np

In [15]:
#### 2. Create a null vector of size 10 (★☆☆)
a = np.zeros(10)

In [17]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [19]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
np.arange(10, 49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [23]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [55]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
indices = np.nonzero([1, 2, 0, 0, 4, 0])
indices

(array([0, 1, 4]),)

In [31]:
#### 7. Create a 3x3 identity matrix (★☆☆)
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
#### 8. Create a 3x3x3 array with random values (★☆☆)
a = np.random.random((3, 3, 3))
a

array([[[0.3870531 , 0.80584844, 0.07273376],
        [0.44373356, 0.23515821, 0.58701712],
        [0.1022437 , 0.95173192, 0.80854401]],

       [[0.50097644, 0.41147454, 0.14448391],
        [0.59308041, 0.96911658, 0.33521281],
        [0.99377117, 0.56492588, 0.52264317]],

       [[0.09308014, 0.34511664, 0.27778146],
        [0.24754032, 0.61391195, 0.47991588],
        [0.58216247, 0.84256068, 0.69703141]]])

In [37]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
array = np.random.random((10, 10))
min_value = array.min()
max_value = array.max()

print("Array:\n", array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)


Array:
 [[0.44888958 0.24822949 0.48523876 0.39950067 0.90886907 0.273852
  0.96535669 0.23705135 0.66737579 0.4586097 ]
 [0.93484025 0.16812102 0.37901467 0.64397372 0.99674691 0.83416266
  0.75811574 0.43992663 0.29520097 0.8042069 ]
 [0.44764757 0.74979964 0.37700696 0.46867089 0.42613137 0.47076659
  0.27159407 0.34187485 0.63035435 0.05415954]
 [0.9168444  0.43584292 0.63399993 0.55738403 0.52632792 0.73063377
  0.08563815 0.29890071 0.49856096 0.49651274]
 [0.33613414 0.23033927 0.19862476 0.74187077 0.98319937 0.71150484
  0.76303867 0.39146266 0.35568754 0.85016601]
 [0.67000798 0.69453112 0.31374979 0.91780016 0.60455868 0.96242734
  0.00164459 0.69218637 0.91192824 0.65545409]
 [0.46860237 0.79551149 0.00240227 0.32362102 0.66288596 0.74438755
  0.89495758 0.53297736 0.17014172 0.31210354]
 [0.76236942 0.49962477 0.74071791 0.31165076 0.76098128 0.7336446
  0.20528331 0.2133404  0.16379488 0.61550025]
 [0.72620593 0.43846015 0.9291523  0.96925747 0.34692358 0.9202839
  0.0733

In [39]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
vector = np.random.random(30)
mean_value = vector.mean()

print("Random vector:", vector)
print("Mean value:", mean_value)

Random vector: [0.7553504  0.73291313 0.60003104 0.95951908 0.48793467 0.77819656
 0.32548594 0.76734394 0.41821003 0.57698546 0.90300161 0.49787616
 0.18469302 0.99104763 0.56237424 0.90551881 0.96599239 0.58961395
 0.44788498 0.79240466 0.84284137 0.67551951 0.30127043 0.64307012
 0.41979998 0.72715337 0.33000978 0.05704993 0.29237401 0.71910426]
Mean value: 0.6083523494334391


In [41]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 
matrix = np.diag([1, 2, 3, 4], k=-1)
matrix

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [43]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
x = np.random.random((5, 5))

mean = matrix.mean()
std = matrix.std()
normalized_matrix = (x - mean) / std

print("Original Matrix:\n", x)
print("Normalized Matrix:\n", normalized_matrix)

Original Matrix:
 [[0.85875897 0.22240611 0.90435921 0.59661399 0.55217872]
 [0.72130315 0.35299    0.39948601 0.32900052 0.56819445]
 [0.40746585 0.10206293 0.59162321 0.97445781 0.92282682]
 [0.47713151 0.8891837  0.73919479 0.57353725 0.69718377]
 [0.90779969 0.1153405  0.39349924 0.43477463 0.82500162]]
Normalized Matrix:
 [[ 4.49850181e-01 -1.74145138e-01  4.94564899e-01  1.92795877e-01
   1.49223511e-01]
 [ 3.15063662e-01 -4.60970997e-02 -5.04004740e-04 -6.96207134e-02
   1.64928227e-01]
 [ 7.32086987e-03 -2.92151334e-01  1.87902016e-01  5.63302232e-01
   5.12673881e-01]
 [ 7.56336676e-02  4.79684081e-01  3.32607859e-01  1.70167278e-01
   2.91412661e-01]
 [ 4.97938561e-01 -2.79131601e-01 -6.37451904e-03  3.40993272e-02
   4.16748372e-01]]


In [45]:
#### 13. How to find common values between two arrays? (★☆☆)
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

common_values = np.intersect1d(array1, array2)
print("Common values:", common_values)

Common values: [4 5]


In [51]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
random_vector = np.random.random(10)
print("Random vector:", random_vector)

sorted_vector = np.sort(vector)
print("Sorted vector:", sorted_vector)

Random vector: [0.85259492 0.96371159 0.22659637 0.50285043 0.3846001  0.98747817
 0.51709178 0.79936513 0.91346303 0.97339083]
Sorted vector: [0.00489111 0.06603625 0.2338977  0.32320287 0.5612443  0.5651483
 0.62776496 0.66486868 0.75091913 0.83305738]


In [53]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
random_vector = np.random.random(10)
max_index = np.argmax(random_vector)

random_vector[max_index] = 0
print("Replaced vector:", random_vector)

Replaced vector: [0.66916179 0.82449374 0.         0.89304388 0.66205636 0.2649368
 0.15042739 0.09368878 0.75523275 0.07910201]


In [61]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
matrix = np.random.random((3, 3))

row_means = matrix.mean(axis=1, keepdims=True)
normalized_matrix = matrix - row_means

print("Original Matrix:\n", matrix)
print("Matrix after subtracting row means:\n", normalized_matrix)

Original Matrix:
 [[0.50132499 0.00562021 0.04496398]
 [0.86834639 0.69795805 0.67464636]
 [0.81034912 0.58344356 0.89992663]]
Matrix after subtracting row means:
 [[ 0.31735526 -0.17834951 -0.13900574]
 [ 0.12136279 -0.04902555 -0.07233724]
 [ 0.04577602 -0.18112954  0.13535353]]


In [69]:
#### 17. How to get the n largest values of an array (★★★)
Z = np.arange(10000)
np.random.shuffle(Z)

n = 5
largest_values = Z[np.argsort(Z)[-n:]]
print("n largest values using np.argsort:", largest_values)

largest_values_argpartition = Z[np.argpartition(Z, -n)[-n:]]
print("n largest values using np.argpartition:", largest_values_argpartition)

n largest values using np.argsort: [9995 9996 9997 9998 9999]
n largest values using np.argpartition: [9995 9996 9997 9998 9999]


In [71]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
matrix = np.random.random((5, 3)) * 10
matrix_modified = np.where(matrix > 4, matrix**2, matrix)

print("Original Matrix:\n", matrix)
print("Modified Matrix:\n", matrix_modified)

Original Matrix:
 [[6.74592727 9.41374603 0.50193516]
 [7.75800139 4.03455802 9.98238291]
 [1.68860919 2.1726451  6.19268338]
 [6.52206625 2.35033936 3.31648573]
 [2.94181241 6.62250044 3.98363747]]
Modified Matrix:
 [[45.50753471 88.61861437  0.50193516]
 [60.18658554 16.27765843 99.64796853]
 [ 1.68860919  2.1726451  38.34932747]
 [42.53734812  2.35033936  3.31648573]
 [ 2.94181241 43.85751211  3.98363747]]
